# Generated by Django 5.0.3 on 2024-05-18 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_extrausuario_delete_infousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='soportetecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_reporte', models.CharField(max_length=50)),
                ('descripcion_reporte', models.CharField(max_length=1000)),
                ('fecha_reporte', models.DateTimeField()),
                ('estado_reporte', models.CharField(max_length=50)),
                ('comentario_soporte', models.CharField(max_length=1000)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
    ]
